var rollListe = [
    "Interdiction de réanimer les alliés.",
    "Vous n'avez le droit à aucuns soins et shields.",
    "Je ne suis pas d'ennemi...",
    "Vous êtes un végétarien des soins et du shield.",
    "Interdit d'utiliser de fusil à pompe.",
    "Droit uniquement aux explosifs.",
    "Uniquement 3 slots disponibles.",
    "Mais ta gueule (raconte sa vie).",
    "Le gris et le vert, deux couleurs magnifiques.",
    "Uniquement le droit aux fusils à pompes.",
    "Stockage d'armes uniquement.",
    "Rainbow (que des raretés différentes)",
    "Compagnon d'arme (doit rester proche d'un allié toute la partie).",
    "Amour propre (Si votre amoureux meurt, alors vous aussi).",
    "Aucun malus, mais échange de malus avec celui qui le réanime.",
    "Maître de terrain (décide de tous les déplacements de la game).",
    "Général en chef (peut donner des ordres à tout le monde).",
    "Interdit de fouiller des coffres.",
    "Unique (la première chose qu'il obtient dans la partie est la rareté obligatoire de toute sa partie).",
    "Piochard (faire un kill avec la pioche).",
    "SoloQ (atterri le plus loin possible de ces alliés et passe la partie seule).",
    "Genshin Launchscreen (prendre le skin le plus fluo de son casier).",
    "Américain (prend le skin le plus gros de son casier).",
    "Âme sensible (interdit de faire des kills).",
    "Cry about it (se plaindre toute la game).",
    "Terminus (se suicide à partir de 20 joueurs restants).",
    "Compte à rebours (doit avoir 4 kills avant qu'il y ait 30 joueurs restants, sinon il se suicide).",
    "Cadenas (interdit de drop des objets de son inventaire).",
    "Arabe (doit voler les objets de ces mates).",
    "Con (donner de faux call à tes mates).",
    "Amnésique (oublie tout, bégaie).",
    "Une petite pièce? (demande à chaque fois qu'il a besoin de ramasser quelque chose sauf les munitions).",
    "Servant (choisis un joueur qui sera son maître).",
    "Egocentrique (se vante de son skill et de celui des alliés).",
    "Abandonné (spawn à un endroit différent de ses alliés et peut les rejoindre que à partir de 50 joueurs restants).",
    "Ange (Priorité de maître, immunise un joueur d'un slot de malus, rajoute +1 ou -1 sur le chiffre d'un autre joueur).",
    "Nomade (interdit d'utiliser des moyens de déplacements comme les véhicules, les grappins et les failles).",
    "Joker (donne à un joueur la possibilité de reroll).",
    "DuoQ (MP une personne avec qui passer la partie en duo).",
    "Medic (seul personne à pouvoir réanimer les joueurs).",
    "Gitano (doit spawn à côté de Lonely Lodge et a le droit uniquement aux AK).",
    "Portugais, inversé (interdit de build).",
    "Petite puissance (uniquement des armes de poing).",
    "Puant (doit rester à une distance raisonnable de ces mates).",
    "Clone (copie le roll de quelqu'un).",
    "Régionnaire (peut seulement ramasser des armes dans son lieu d'atterrissage).",
    "Rassuré (se précipite vers la safe zone en priorité).",
    "Retardataire (attend la fin du bus).",
    "Switcher (inverse les rolls de deux joueurs).",
    "Masochist (peut se heal la vie et le shield que à partir du moment où il lui reste 30HP).",
    "Décision (connait tous les roll des joueurs: peut rajouter un roll aléatoire à tout le monde ou alors subir leurs rolls).",
    "Kamikaze (doit faire un kill avec un explosif et mourir en même temps).",
    "Troll (danse pendant 3 secondes avant de réanimer un allié).",
    "Maire (doit atterrir au bâtiment principal et ces alliés lui doit du build).",
    "Mineur (doit avoir le maximum de build d'une catégorie avant de pouvoir ramasser des objets).",
    "Collectionneur (la première arme qu'il ramasse est la seule de toute la partie, il peut stocker plusieurs raretés de celle-ci).",
    "MINCE ALORS (reroll tout le monde).",
    "Dégagez (le dire quand on peut sauter du bus, tout le monde saute du bus).",
    "Influence (si un allié est à terre, alors vous ne pouvez plus tirer).",
    "Fatal (vous devez vous mettre K.O avant de pouvoir ramasser des objets tout le reste de la partie).",
    "Convoi (les alliés doivent le protéger toute la partie, si il meurt, ces alliés aussi).",
    "Traître (doit tout faire pour éliminer son équipe).",
    "SDF (interdit de rentrer dans les bâtiments).",
    "Bambi (casier vide sauf les danses et autres non visibles).",
    "Détachement total (toute la squad atterri a des villes différentes).",
    "DeFaillance (deux emplacements réservés à des failles de poches).",
    "Focus (colle un allié toute la partie).",
    "AR 0 (interdit aux fusils d'assauts).",
    "Touriste (parler en anglais).",
    "Raciste (parler de façon raciste).",
    "Silence absolu (tout le monde parle en chuchotant).",
    "Désigné (choisit une personne ou soit même pour aller seul à Tilted Tower).",
    "Surchauffe (doit overbuild à chaque fight)"
    ] ;
    
    function Roll()
    {
        var alea = Math.floor(Math.random() * rollListe.length);
        var defiChoisi = rollListe[alea];
        document.getElementById("texteX").innerHTML = Number(alea) + 1 ;
        document.getElementById("txtdfi").innerHTML = defiChoisi;
    }
    // v23.11.2023 21:06